
keys = {
        'acx':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'allcoin':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'bibox':{
                'public':'',
                'private':'',
                'extra_params':{
                        'name':''
                         },
                    },
        'binance':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'bitbay':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'bitfinex':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'bitlish':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'bitmex':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'bitstamp':{
                'public':'',
                'private':'',
                'extra_params':{
                        'uid':''
                            }
                    },
        'bittrex':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'bleutrade':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'cryptopia':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'dsx':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'exmo':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'gateio':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'gemini':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'hitbtc':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },       
        'kraken':{
                'public':'',
                'private':'',
                'extra_params':{
                           }
                    },
        'huobipro':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'kucoin':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'liqui':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'livecoin':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'poloniex':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'quadrigacx':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'southxchange':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'tidex':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'yobit':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'zaif':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    },
        'zb':{
                'public':'',
                'private':'',
                'extra_params':{
                          }
                    }
        }  
